export const SEARCH_CHANGE = "SEARCH_CHANGE";

export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_REQUEST_SUCCESS = "SEARCH_REQUEST_SUCCESS";
export const SEARCH_REQUEST_FAILURE = "SEARCH_REQUEST_FAILURE";

export const LOOKUP_REQUEST = "LOOKUP_REQUEST";
export const LOOKUP_REQUEST_SUCCESS = "LOOKUP_REQUEST_SUCCESS";
export const LOOKUP_REQUEST_FAILURE = "LOOKUP_REQUEST_FAILURE";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";
